from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
      migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('client_id',models.CharField(max_length=64,unique=True)),('nickname',models.CharField(max_length=80)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
      migrations.CreateModel(name='Ride',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('mode',models.CharField(choices=[('taxi','計程車'),('drive','自駕')],default='taxi',max_length=10)),('status',models.CharField(choices=[('open','募集中'),('full','已額滿'),('cancelled','已取消'),('finished','已完成')],default='open',max_length=12)),('ride_date',models.DateField()),('ride_time',models.TimeField()),('max_people',models.PositiveSmallIntegerField(default=3)),('meeting_name',models.CharField(max_length=160)),('meeting_lat',models.FloatField(blank=True,null=True)),('meeting_lng',models.FloatField(blank=True,null=True)),('destination_name',models.CharField(max_length=160)),('destination_lat',models.FloatField(blank=True,null=True)),('destination_lng',models.FloatField(blank=True,null=True)),('estimated_total',models.PositiveIntegerField(default=120)),('price_per_person',models.PositiveIntegerField(default=0)),('plate',models.CharField(blank=True,max_length=20)),('vehicle',models.CharField(blank=True,max_length=80)),('note',models.TextField(blank=True)),('locked',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('owner',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='owned_rides',to='rides.profile'))],options={'ordering':['-created_at']}),
      migrations.CreateModel(name='RideMember',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(default='member',max_length=10)),('joined_at',models.DateTimeField(auto_now_add=True)),('profile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='rides.profile')),('ride',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='rides.ride'))]),
      migrations.AddField(model_name='ride',name='members',field=models.ManyToManyField(related_name='rides',through='rides.RideMember',to='rides.profile')),
      migrations.CreateModel(name='Message',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('text',models.CharField(max_length=1000)),('created_at',models.DateTimeField(auto_now_add=True)),('ride',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='messages',to='rides.ride')),('sender',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='rides.profile'))],options={'ordering':['created_at']}),
      migrations.CreateModel(name='Location',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('lat',models.FloatField()),('lng',models.FloatField()),('accuracy',models.FloatField(blank=True,null=True)),('updated_at',models.DateTimeField(auto_now=True)),('profile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='rides.profile')),('ride',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='locations',to='rides.ride'))]),
      migrations.AddConstraint(model_name='ridemember',constraint=models.UniqueConstraint(fields=('ride','profile'),name='uniq_ride_member')),
      migrations.AddConstraint(model_name='location',constraint=models.UniqueConstraint(fields=('ride','profile'),name='uniq_ride_location')),
    ]
